[workspace]
members = [
    "module_1/mod_1_exercises",
    "module_2/mod_2_exercises",
    "module_3/mod_3_exercises",
    "module_4/mod_4_exercises",
    "module_5/serde1",
    "module_5/serde2_hashmap",
    "module_5/serde2_vector",
    "module_5/serde3",
]
